@startuml

package "Ubuntu" {
  [atp]
  [linux_brew]
}

package "MacOs" {
  [brew]
}

frame "Available Packages" {
  (apt_packages)
  (brew_packages)
}

apt_packages --> atp : atp install
brew_packages --> linux_brew : brew install
apt_packages --> brew : brew install
brew_packages --> brew : brew install
@enduml